'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BookMaster
    Public Property Id As Integer
    Public Property strBookTypeId As String
    Public Property strAccessionId As String

    Public Overridable Property Publishers As ICollection(Of Publisher) = New HashSet(Of Publisher)

End Class
