'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Publisher
    Public Property PublisherId As String
    Public Property PublisherName As String
    Public Property PublishingYear As Date
    Public Property BookMaster_Id As Nullable(Of Integer)

    Public Overridable Property BookMaster As BookMaster

End Class
